language: python

python:
  - "3.6"

sudo: false

before_install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip

install:
  - pip install .

script:
  - cd tests/unit
  - PYTHONPATH=../..:.. ./run_tests.py
